### ISSUE TITLE
AttributeError: module 'image_processing' has no attribute 'image_processing'

### ISSUE THREAD

**Issue by ayushmankumar7** [Skalextric/kivy_cv#2]
![Screenshot from 2019-03-17 21-47-21](https://user-images.githubusercontent.com/41910134/54494273-6aab1200-48fe-11e9-9d17-cceb603ec79d.png)

This Error i got when i ran opencv.py

**Comment by 4mosoT** [comment]
It was a problem with the new OpenCV versions. This repo was a bit outdated. It should work now.

**Comment by ayushmankumar7** [comment]
It's Still not working
