### ISSUE TITLE
File "/home/ayushman/Documents/Github/kivy_cv/image_processing/image_processing.py", line 19, in face_detection      faceRects = detector.detectMultiScale(gray,1.1,5 )  cv2.error: OpenCV(4.0.0) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

### ISSUE THREAD

**Issue by ayushmankumar7** [Skalextric/kivy_cv#3]
![Screenshot from 2019-03-18 14-25-16](https://user-images.githubusercontent.com/41910134/54518165-ae972900-4989-11e9-84a4-0d1100c73b2b.png)

As soon as in press the detect Face Button, the app crashes.

**Comment by 4mosoT** [comment]
Does it show the cam image in first place?

**Comment by ayushmankumar7** [comment]
No initially It didn't ..  Then i did some changes to enable the Camera.
I tried to push my changes but it's showing access denied.

**Comment by 4mosoT** [comment]
Is seems you don't have permissions to open the camera. As soon as you fix this it'll work. Try changing the integer in "cap = cv2.VideoCapture(0)" in cv_camera.py.

**Comment by ayushmankumar7** [comment]
I can open my camera ...
It's working fine until i press Detect Face.

**Comment by 4mosoT** [comment]
Check the path of the cascades xml file
